### ISSUE TITLE
intermittent segfault

### ISSUE THREAD

**Issue by doppelreim** [YorickPeterse/ffi-aspell#22]
Hi :)
I am getting segfaults, when querying suggestions for "--" in german... sometimes :/

Using ruby 2.2.2 with ffi-aspell 1.1.0
And ruby 2.1.2 with ffi-aspell 1.0.2

I tried querying for suggestions in english, french and italian. Works fine, so far.
Querying for other words in german works as well.

Here is a minimal script to reproduce the problem.
For me, on average, only every 5th run segfaults.
```
require 'ffi/aspell'

language = "de"
word = "--"

speller = FFI::Aspell::Speller.new(language, encoding: "utf-8")

p speller.suggestions(word)
```

Here is the output of the segfault:
```
$ ruby aspell_test.rb 
/home/mroemer/.gem/ruby/2.2.2/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb:243: [BUG] Segmentation fault at 0x00000000000000
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0021 e:000020 CFUNC  :speller_suggest
c:0003 p:0070 s:0015 e:000014 METHOD /home/mroemer/.gem/ruby/2.2.2/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb:243
c:0002 p:0050 s:0008 E:000bf8 EVAL   aspell_test.rb:8 [FINISH]
c:0001 p:0000 s:0002 E:000ad0 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
aspell_test.rb:8:in `<main>'
/home/mroemer/.gem/ruby/2.2.2/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb:243:in `suggestions'
/home/mroemer/.gem/ruby/2.2.2/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb:243:in `speller_suggest'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f323f3e33be RBP: 0x0000000000000000 RSP: 0x00007fff46d8fdf0
 RAX: 0x0000000000000000 RBX: 0x00007fff46d90048 RCX: 0x00007fff46d90047
 RDX: 0x0000000000000000 RDI: 0x00007fff46d8fda8 RSI: 0x0000000000000002
  R8: 0x0000000000000000  R9: 0x00007fff46d8fd60 R10: 0x0000000000000010
 R11: 0x0000000000000000 R12: 0x0000000000000000 R13: 0x0000000000000000
 R14: 0x00007f3242585b2f R15: 0x0000000000000000 EFL: 0x0000000000010246

-- C level backtrace information -------------------------------------------
/home/mroemer/.rubies/ruby-2.2.2/bin/ruby(rb_vm_bugreport+0x51f) [0x7f3241555e2f] vm_dump.c:693
/home/mroemer/.rubies/ruby-2.2.2/bin/ruby(rb_bug_context+0xcb) [0x7f32415c78ab] error.c:425
/home/mroemer/.rubies/ruby-2.2.2/bin/ruby(sigsegv+0x3e) [0x7f32414c625e] signal.c:879
/lib/x86_64-linux-gnu/libpthread.so.0 [0x7f3240fa5340]
/usr/lib/libaspell.so.15(_ZNK8aspeller8AffixMgr12suffix_checkERKNS_10LookupInfoEN7acommon10ParmStringERNS4_9CheckInfoEPNS_9GuessInfoEiPNS_8AffEntryE+0x1de) [0x7f323f3e33be]
/usr/lib/libaspell.so.15(_ZNK8aspeller8AffixMgr11affix_checkERKNS_10LookupInfoEN7acommon10ParmStringERNS4_9CheckInfoEPNS_9GuessInfoE+0x12d) [0x7f323f3e399d]
/usr/lib/libaspell.so.15 [0x7f323f3bbba7]
/usr/lib/libaspell.so.15 [0x7f323f3c1775]
/usr/lib/libaspell.so.15(_ZN8aspeller11SpellerImpl7suggestEN7acommon13MutableStringE+0x14) [0x7f323f3cf984]
/usr/lib/libaspell.so.15(aspell_speller_suggest+0x6f) [0x7f323f3fae0f]
/usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f323f623adc]
/usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x1fc) [0x7f323f62340c]
/home/mroemer/.gem/ruby/2.2.2/extensions/x86_64-linux/2.2.0-static/ffi-1.9.8/ffi_c.so(rbffi_CallFunction+0x110) [0x7f323f82f8a0] Call.c:443
/home/mroemer/.gem/ruby/2.2.2/extensions/x86_64-linux/2.2.0-static/ffi-1.9.8/ffi_c.so(custom_trampoline+0x16) [0x7f323f82fd26] MethodHandle.c:232
/home/mroemer/.rubies/ruby-2.2.2/bin/ruby(vm_call_cfunc+0x11e) [0x7f324153d81e] vm_insnhelper.c:1382
/home/mroemer/.rubies/ruby-2.2.2/bin/ruby(vm_call_method+0x11e) [0x7f324154bb6e] vm_insnhelper.c:1691
/home/mroemer/.rubies/ruby-2.2.2/bin/ruby(vm_exec_core+0x203a) [0x7f3241542d4a] insns.def:1054
/home/mroemer/.rubies/ruby-2.2.2/bin/ruby(vm_exec+0x84) [0x7f32415465b4] vm.c:1400
/home/mroemer/.rubies/ruby-2.2.2/bin/ruby(rb_iseq_eval_main+0x1f3) [0x7f3241553413] vm.c:1670
/home/mroemer/.rubies/ruby-2.2.2/bin/ruby(ruby_exec_internal+0xc4) [0x7f32413fc394] eval.c:252
/home/mroemer/.rubies/ruby-2.2.2/bin/ruby(ruby_run_node+0x2d) [0x7f32413fff2d] eval.c:317
/home/mroemer/.rubies/ruby-2.2.2/bin/ruby(main+0x4b) [0x7f32413fbf2b] parse.y:8795

-- Other runtime information -----------------------------------------------

* Loaded script: aspell_test.rb

* Loaded features:

    0 enumerator.so
    1 rational.so
    2 complex.so
    3 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/enc/encdb.so
    4 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/enc/trans/transdb.so
    5 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/unicode_normalize.rb
    6 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/rbconfig.rb
    7 thread.rb
    8 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/thread.so
    9 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/compatibility.rb
   10 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/defaults.rb
   11 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/deprecate.rb
   12 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/errors.rb
   13 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/version.rb
   14 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/requirement.rb
   15 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/platform.rb
   16 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/basic_specification.rb
   17 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/stub_specification.rb
   18 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/util/stringio.rb
   19 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/specification.rb
   20 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/exceptions.rb
   21 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb
   22 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb
   23 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb
   24 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems.rb
   25 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/path_support.rb
   26 /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/dependency.rb
   27 /home/mroemer/.gem/ruby/2.2.2/extensions/x86_64-linux/2.2.0-static/ffi-1.9.8/ffi_c.so
   28 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/platform.rb
   29 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/types.rb
   30 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/library.rb
   31 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/errno.rb
   32 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/pointer.rb
   33 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/memorypointer.rb
   34 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/struct_layout_builder.rb
   35 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/struct.rb
   36 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/union.rb
   37 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/managedstruct.rb
   38 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/callback.rb
   39 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/io.rb
   40 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/autopointer.rb
   41 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/variadic.rb
   42 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/enum.rb
   43 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi/ffi.rb
   44 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-1.9.8/lib/ffi.rb
   45 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-aspell-1.1.0/lib/ffi/aspell/aspell.rb
   46 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-aspell-1.1.0/lib/ffi/aspell/error.rb
   47 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb
   48 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-aspell-1.1.0/lib/ffi/aspell/version.rb
   49 /home/mroemer/.gem/ruby/2.2.2/gems/ffi-aspell-1.1.0/lib/ffi/aspell.rb

* Process memory map:

7f323db5b000-7f323dd1d000 r--s 00000000 fc:01 24379593                   /lib/x86_64-linux-gnu/libc-2.19.so
7f323dd1d000-7f323de0a000 r--s 00000000 fc:01 13502257                   /home/mroemer/.gem/ruby/2.2.2/extensions/x86_64-linux/2.2.0-static/ffi-1.9.8/ffi_c.so
7f323de0a000-7f323dec5000 r--s 00000000 fc:01 17042324                   /usr/lib/libaspell.so.15.2.0
7f323dec5000-7f323ec6c000 r--s 00000000 fc:01 5907522                    /home/mroemer/.rubies/ruby-2.2.2/bin/ruby
7f323ec6c000-7f323ee41000 r--s 00000000 fc:01 7356308                    /var/lib/aspell/de-common.rws
7f323ee41000-7f323ee57000 r-xp 00000000 fc:01 24383518                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f323ee57000-7f323f056000 ---p 00016000 fc:01 24383518                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f323f056000-7f323f057000 rw-p 00015000 fc:01 24383518                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f323f057000-7f323f13d000 r-xp 00000000 fc:01 17039751                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
7f323f13d000-7f323f33c000 ---p 000e6000 fc:01 17039751                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
7f323f33c000-7f323f344000 r--p 000e5000 fc:01 17039751                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
7f323f344000-7f323f346000 rw-p 000ed000 fc:01 17039751                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
7f323f346000-7f323f35b000 rw-p 00000000 00:00 0 
7f323f35b000-7f323f410000 r-xp 00000000 fc:01 17042324                   /usr/lib/libaspell.so.15.2.0
7f323f410000-7f323f60f000 ---p 000b5000 fc:01 17042324                   /usr/lib/libaspell.so.15.2.0
7f323f60f000-7f323f615000 r--p 000b4000 fc:01 17042324                   /usr/lib/libaspell.so.15.2.0
7f323f615000-7f323f616000 rw-p 000ba000 fc:01 17042324                   /usr/lib/libaspell.so.15.2.0
7f323f616000-7f323f61e000 rw-p 00000000 00:00 0 
7f323f61e000-7f323f625000 r-xp 00000000 fc:01 17047124                   /usr/lib/x86_64-linux-gnu/libffi.so.6.0.1
7f323f625000-7f323f824000 ---p 00007000 fc:01 17047124                   /usr/lib/x86_64-linux-gnu/libffi.so.6.0.1
7f323f824000-7f323f825000 r--p 00006000 fc:01 17047124                   /usr/lib/x86_64-linux-gnu/libffi.so.6.0.1
7f323f825000-7f323f826000 rw-p 00007000 fc:01 17047124                   /usr/lib/x86_64-linux-gnu/libffi.so.6.0.1
7f323f826000-7f323f847000 r-xp 00000000 fc:01 13502257                   /home/mroemer/.gem/ruby/2.2.2/extensions/x86_64-linux/2.2.0-static/ffi-1.9.8/ffi_c.so
7f323f847000-7f323fa46000 ---p 00021000 fc:01 13502257                   /home/mroemer/.gem/ruby/2.2.2/extensions/x86_64-linux/2.2.0-static/ffi-1.9.8/ffi_c.so
7f323fa46000-7f323fa47000 r--p 00020000 fc:01 13502257                   /home/mroemer/.gem/ruby/2.2.2/extensions/x86_64-linux/2.2.0-static/ffi-1.9.8/ffi_c.so
7f323fa47000-7f323fa48000 rw-p 00021000 fc:01 13502257                   /home/mroemer/.gem/ruby/2.2.2/extensions/x86_64-linux/2.2.0-static/ffi-1.9.8/ffi_c.so
7f323fa48000-7f323fa49000 rw-p 00000000 00:00 0 
7f323fa49000-7f323fa4c000 r-xp 00000000 fc:01 5907677                    /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/thread.so
7f323fa4c000-7f323fc4c000 ---p 00003000 fc:01 5907677                    /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/thread.so
7f323fc4c000-7f323fc4d000 r--p 00003000 fc:01 5907677                    /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/thread.so
7f323fc4d000-7f323fc4e000 rw-p 00004000 fc:01 5907677                    /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/thread.so
7f323fc4e000-7f323fc50000 r-xp 00000000 fc:01 7086472                    /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/enc/trans/transdb.so
7f323fc50000-7f323fe50000 ---p 00002000 fc:01 7086472                    /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/enc/trans/transdb.so
7f323fe50000-7f323fe51000 r--p 00002000 fc:01 7086472                    /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/enc/trans/transdb.so
7f323fe51000-7f323fe52000 rw-p 00003000 fc:01 7086472                    /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/enc/trans/transdb.so
7f323fe52000-7f323fe54000 r-xp 00000000 fc:01 7086493                    /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/enc/encdb.so
7f323fe54000-7f3240053000 ---p 00002000 fc:01 7086493                    /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/enc/encdb.so
7f3240053000-7f3240054000 r--p 00001000 fc:01 7086493                    /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/enc/encdb.so
7f3240054000-7f3240055000 rw-p 00002000 fc:01 7086493                    /home/mroemer/.rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/enc/encdb.so
7f3240055000-7f324048d000 r--p 00000000 fc:01 17045653                   /usr/lib/locale/locale-archive
7f324048d000-7f3240648000 r-xp 00000000 fc:01 24379593                   /lib/x86_64-linux-gnu/libc-2.19.so
7f3240648000-7f3240847000 ---p 001bb000 fc:01 24379593                   /lib/x86_64-linux-gnu/libc-2.19.so
7f3240847000-7f324084b000 r--p 001ba000 fc:01 24379593                   /lib/x86_64-linux-gnu/libc-2.19.so
7f324084b000-7f324084d000 rw-p 001be000 fc:01 24379593                   /lib/x86_64-linux-gnu/libc-2.19.so
7f324084d000-7f3240852000 rw-p 00000000 00:00 0 
7f3240852000-7f3240957000 r-xp 00000000 fc:01 24379578                   /lib/x86_64-linux-gnu/libm-2.19.so
7f3240957000-7f3240b56000 ---p 00105000 fc:01 24379578                   /lib/x86_64-linux-gnu/libm-2.19.so
7f3240b56000-7f3240b57000 r--p 00104000 fc:01 24379578                   /lib/x86_64-linux-gnu/libm-2.19.so
7f3240b57000-7f3240b58000 rw-p 00105000 fc:01 24379578                   /lib/x86_64-linux-gnu/libm-2.19.so
7f3240b58000-7f3240b61000 r-xp 00000000 fc:01 24379585                   /lib/x86_64-linux-gnu/libcrypt-2.19.so
7f3240b61000-7f3240d61000 ---p 00009000 fc:01 24379585                   /lib/x86_64-linux-gnu/libcrypt-2.19.so
7f3240d61000-7f3240d62000 r--p 00009000 fc:01 24379585                   /lib/x86_64-linux-gnu/libcrypt-2.19.so
7f3240d62000-7f3240d63000 rw-p 0000a000 fc:01 24379585                   /lib/x86_64-linux-gnu/libcrypt-2.19.so
7f3240d63000-7f3240d91000 rw-p 00000000 00:00 0 
7f3240d91000-7f3240d94000 r-xp 00000000 fc:01 24379582                   /lib/x86_64-linux-gnu/libdl-2.19.so
7f3240d94000-7f3240f93000 ---p 00003000 fc:01 24379582                   /lib/x86_64-linux-gnu/libdl-2.19.so
7f3240f93000-7f3240f94000 r--p 00002000 fc:01 24379582                   /lib/x86_64-linux-gnu/libdl-2.19.so
7f3240f94000-7f3240f95000 rw-p 00003000 fc:01 24379582                   /lib/x86_64-linux-gnu/libdl-2.19.so
7f3240f95000-7f3240fae000 r-xp 00000000 fc:01 24379594                   /lib/x86_64-linux-gnu/libpthread-2.19.so
7f3240fae000-7f32411ad000 ---p 00019000 fc:01 24379594                   /lib/x86_64-linux-gnu/libpthread-2.19.so
7f32411ad000-7f32411ae000 r--p 00018000 fc:01 24379594                   /lib/x86_64-linux-gnu/libpthread-2.19.so
7f32411ae000-7f32411af000 rw-p 00019000 fc:01 24379594                   /lib/x86_64-linux-gnu/libpthread-2.19.so
7f32411af000-7f32411b3000 rw-p 00000000 00:00 0 
7f32411b3000-7f32411d6000 r-xp 00000000 fc:01 24379590                   /lib/x86_64-linux-gnu/ld-2.19.so
7f3241289000-7f32412ac000 r--s 00000000 fc:01 24379594                   /lib/x86_64-linux-gnu/libpthread-2.19.so
7f32412ac000-7f32413b1000 rw-p 00000000 00:00 0 
7f32413b9000-7f32413c1000 r--s 00000000 fc:01 17047124                   /usr/lib/x86_64-linux-gnu/libffi.so.6.0.1
7f32413c1000-7f32413cb000 r--s 00000000 fc:01 7356311                    /var/lib/aspell/de_DE-only.rws
7f32413cd000-7f32413ce000 rw-p 00000000 00:00 0 
7f32413ce000-7f32413cf000 r-xp 00000000 00:00 0 
7f32413cf000-7f32413d0000 ---p 00000000 00:00 0 
7f32413d0000-7f32413d5000 rw-p 00000000 00:00 0                          [stack:4197]
7f32413d5000-7f32413d6000 r--p 00022000 fc:01 24379590                   /lib/x86_64-linux-gnu/ld-2.19.so
7f32413d6000-7f32413d7000 rw-p 00023000 fc:01 24379590                   /lib/x86_64-linux-gnu/ld-2.19.so
7f32413d7000-7f32413d8000 rw-p 00000000 00:00 0 
7f32413d8000-7f32416ad000 r-xp 00000000 fc:01 5907522                    /home/mroemer/.rubies/ruby-2.2.2/bin/ruby
7f32418ad000-7f32418b2000 r--p 002d5000 fc:01 5907522                    /home/mroemer/.rubies/ruby-2.2.2/bin/ruby
7f32418b2000-7f32418b3000 rw-p 002da000 fc:01 5907522                    /home/mroemer/.rubies/ruby-2.2.2/bin/ruby
7f32418b3000-7f32418c5000 rw-p 00000000 00:00 0 
7f324206c000-7f324259a000 rw-p 00000000 00:00 0                          [heap]
7fff46594000-7fff46d93000 rw-p 00000000 00:00 0 
7fff46dfe000-7fff46e00000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Aborted
```

**Comment by YorickPeterse** [comment]
I wouldn't be surprised if this is Aspell itself not being able to analyse such text. Looking at the error it indeed seems to originate from libaspell itself:

```
/usr/lib/libaspell.so.15(_ZNK8aspeller8AffixMgr12suffix_checkERKNS_10LookupInfoEN7acommon10ParmStringERNS4_9CheckInfoEPNS_9GuessInfoEiPNS_8AffEntryE+0x1de) [0x7f323f3e33be]
/usr/lib/libaspell.so.15(_ZNK8aspeller8AffixMgr11affix_checkERKNS_10LookupInfoEN7acommon10ParmStringERNS4_9CheckInfoEPNS_9GuessInfoE+0x12d) [0x7f323f3e399d]
/usr/lib/libaspell.so.15 [0x7f323f3bbba7]
/usr/lib/libaspell.so.15 [0x7f323f3c1775]
/usr/lib/libaspell.so.15(_ZN8aspeller11SpellerImpl7suggestEN7acommon13MutableStringE+0x14) [0x7f323f3cf984]
/usr/lib/libaspell.so.15(aspell_speller_suggest+0x6f) [0x7f323f3fae0f]
```

Not sure what/if there's anything this Gem can do to prevent this from happening.

**Comment by doppelreim** [comment]
Oh, ok... I'll try to reprodue it directly in aspell and see if I can find someone to report it to.

Thanks for clearing it up!
