### ISSUE TITLE
Usage on windows (with Aspell win32)

### ISSUE THREAD

**Issue by UltraGit** [YorickPeterse/ffi-aspell#23]
Having trouble getting the .dll references to work in windows.  Have Aspell 0.50 (last win32 package) on Win8 and running rubymine with a basic script to test it: 

 (LoadError)
.
Could not open library 'aspell.dll': The specified module could not be found.
.
Could not open library 'libaspell.so.15': The specified module could not be found.
.
Could not open library 'libaspell.so.15.dll': The specified module could not be found.
	from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi/library.rb:100:in `map'
	from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
	from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/aspell.rb:17:in `<module:Aspell>'
	from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/aspell.rb:15:in `<module:FFI>'
	from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/aspell.rb:1:in `<top (required)>'
	from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell.rb:3:in `require_relative'
	from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell.rb:3:in `<top (required)>'

**Comment by YorickPeterse** [comment]
Windows probably uses a different name for the library. I don't have access to a Windows system, nor have I ever tested ffi-aspell on Windows. If you can figure out the actual library name a pull request to add it is more than welcome.

**Comment by fireundubh** [comment]
The Win32 DLL is named `aspell-15.dll`.
