### ISSUE TITLE
Error on OSX installation

### ISSUE THREAD

**Issue by petems** [YorickPeterse/ffi-aspell#26]
I'm getting an error when trying to use the bindings:

```
$ ruby -e "require 'ffi/aspell'; s = FFI::Aspell::Speller.new('en'); s.correct?('car')"
/opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'aspell': dlopen(aspell, 5): image not found. (LoadError)
Could not open library 'libaspell.dylib': dlopen(libaspell.dylib, 5): image not found.
Could not open library 'libaspell.so.15': dlopen(libaspell.so.15, 5): image not found.
Could not open library 'libaspell.so.15.dylib': dlopen(libaspell.so.15.dylib, 5): image not found
	from /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `map'
	from /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `ffi_lib'
	from /opt/rubies/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/aspell.rb:17:in `<module:Aspell>'
	from /opt/rubies/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/aspell.rb:15:in `<module:FFI>'
	from /opt/rubies/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/aspell.rb:1:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell.rb:3:in `require_relative'
	from /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell.rb:3:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from -e:1:in `<main>'
```

I'm assuming this is a pathing issue with brew, but everything seems to be installed as normal:

```
brew install aspell --lang=en
Warning: aspell-0.60.6.1 already installed
```

**Comment by YorickPeterse** [comment]
What is the library name (libaspell.so.foo, libaspell.dylib.whatever, etc) of aspell on your system?

**Comment by petems** [comment]
@YorickPeterse How do I find that out?

**Comment by YorickPeterse** [comment]
@petems At least on Linux you can do something like this:

```
~ $ ls -alh /usr/lib/ | grep -i aspell
lrwxrwxrwx   1 root root    11 Apr 27  2016 aspell -> aspell-0.60
drwxr-xr-x   2 root root   12K Jul 10  2016 aspell-0.60
lrwxrwxrwx   1 root root    19 Apr 27  2016 libaspell.so -> libaspell.so.15.1.5
lrwxrwxrwx   1 root root    19 Apr 27  2016 libaspell.so.15 -> libaspell.so.15.1.5
-rwxr-xr-x   1 root root  695K Apr 27  2016 libaspell.so.15.1.5
```

So for me `libaspell.so` seems like the most reasonable candidate since it doesn't contain a version identifier (meaning you don't have to update the Ruby code every release).

For OS X I'm not sure where the `.dylib` files would be stored unfortunately.

**Comment by petems** [comment]
From brew it's here: `/opt/boxen/homebrew/Cellar/aspell/0.60.6.1`

Full tree of the directory:

```
13:30:43 /opt/boxen/homebrew/Cellar/aspell/0.60.6.1 (stable) $ tree
.
├── COPYING
├── INSTALL_RECEIPT.json
├── README
├── TODO
├── bin
│   ├── aspell
│   ├── aspell-import
│   ├── precat
│   ├── preunzip
│   ├── prezip
│   ├── prezip-bin
│   ├── pspell-config
│   ├── run-with-aspell
│   └── word-list-compress
├── include
│   ├── aspell.h
│   └── pspell
│       └── pspell.h
├── lib
│   ├── aspell-0.60
│   │   ├── american-variant_0.alias
│   │   ├── american-variant_1.alias
│   │   ├── american-w_accents.alias
│   │   ├── american-wo_accents.alias
│   │   ├── american.alias
│   │   ├── british-ise-w_accents.alias
│   │   ├── british-ise-wo_accents.alias
│   │   ├── british-ise.alias
│   │   ├── british-ize-w_accents.alias
│   │   ├── british-ize-wo_accents.alias
│   │   ├── british-ize.alias
│   │   ├── british-variant_0.alias
│   │   ├── british-variant_1.alias
│   │   ├── british-w_accents.alias
│   │   ├── british-wo_accents.alias
│   │   ├── british.alias
│   │   ├── canadian-variant_0.alias
│   │   ├── canadian-variant_1.alias
│   │   ├── canadian-w_accents.alias
│   │   ├── canadian-wo_accents.alias
│   │   ├── canadian.alias
│   │   ├── ccpp.amf
│   │   ├── comment.amf
│   │   ├── context-filter.info
│   │   ├── context-filter.so
│   │   ├── cp1250.cmap
│   │   ├── cp1250.cset
│   │   ├── cp1251.cmap
│   │   ├── cp1251.cset
│   │   ├── cp1252.cmap
│   │   ├── cp1252.cset
│   │   ├── cp1253.cmap
│   │   ├── cp1253.cset
│   │   ├── cp1254.cmap
│   │   ├── cp1254.cset
│   │   ├── cp1255.cmap
│   │   ├── cp1255.cset
│   │   ├── cp1256.cmap
│   │   ├── cp1256.cset
│   │   ├── cp1257.cmap
│   │   ├── cp1257.cset
│   │   ├── cp1258.cmap
│   │   ├── cp1258.cset
│   │   ├── dvorak.kbd
│   │   ├── email-filter.info
│   │   ├── email-filter.so
│   │   ├── email.amf
│   │   ├── en-common.rws
│   │   ├── en-variant_0.multi
│   │   ├── en-variant_0.rws
│   │   ├── en-variant_1.multi
│   │   ├── en-variant_1.rws
│   │   ├── en-variant_2.multi
│   │   ├── en-variant_2.rws
│   │   ├── en-w_accents-only.rws
│   │   ├── en-w_accents.multi
│   │   ├── en-wo_accents-only.rws
│   │   ├── en-wo_accents.multi
│   │   ├── en.dat
│   │   ├── en.multi
│   │   ├── en_CA-variant_0.multi
│   │   ├── en_CA-variant_0.rws
│   │   ├── en_CA-variant_1.multi
│   │   ├── en_CA-variant_1.rws
│   │   ├── en_CA-w_accents-only.rws
│   │   ├── en_CA-w_accents.multi
│   │   ├── en_CA-wo_accents-only.rws
│   │   ├── en_CA-wo_accents.multi
│   │   ├── en_CA.multi
│   │   ├── en_GB-ise-w_accents-only.rws
│   │   ├── en_GB-ise-w_accents.multi
│   │   ├── en_GB-ise-wo_accents-only.rws
│   │   ├── en_GB-ise-wo_accents.multi
│   │   ├── en_GB-ise.multi
│   │   ├── en_GB-ize-w_accents-only.rws
│   │   ├── en_GB-ize-w_accents.multi
│   │   ├── en_GB-ize-wo_accents-only.rws
│   │   ├── en_GB-ize-wo_accents.multi
│   │   ├── en_GB-ize.multi
│   │   ├── en_GB-variant_0.multi
│   │   ├── en_GB-variant_0.rws
│   │   ├── en_GB-variant_1.multi
│   │   ├── en_GB-variant_1.rws
│   │   ├── en_GB-w_accents.multi
│   │   ├── en_GB-wo_accents.multi
│   │   ├── en_GB.multi
│   │   ├── en_US-variant_0.multi
│   │   ├── en_US-variant_1.multi
│   │   ├── en_US-w_accents-only.rws
│   │   ├── en_US-w_accents.multi
│   │   ├── en_US-wo_accents-only.rws
│   │   ├── en_US-wo_accents.multi
│   │   ├── en_US.multi
│   │   ├── en_affix.dat
│   │   ├── en_phonet.dat
│   │   ├── english-variant_0.alias
│   │   ├── english-variant_1.alias
│   │   ├── english-variant_2.alias
│   │   ├── english-w_accents.alias
│   │   ├── english-wo_accents.alias
│   │   ├── english.alias
│   │   ├── html-filter.info
│   │   ├── html.amf
│   │   ├── iso-8859-1.cmap
│   │   ├── iso-8859-1.cset
│   │   ├── iso-8859-10.cmap
│   │   ├── iso-8859-10.cset
│   │   ├── iso-8859-11.cmap
│   │   ├── iso-8859-11.cset
│   │   ├── iso-8859-13.cmap
│   │   ├── iso-8859-13.cset
│   │   ├── iso-8859-14.cmap
│   │   ├── iso-8859-14.cset
│   │   ├── iso-8859-15.cmap
│   │   ├── iso-8859-15.cset
│   │   ├── iso-8859-16.cmap
│   │   ├── iso-8859-16.cset
│   │   ├── iso-8859-2.cmap
│   │   ├── iso-8859-2.cset
│   │   ├── iso-8859-3.cmap
│   │   ├── iso-8859-3.cset
│   │   ├── iso-8859-4.cmap
│   │   ├── iso-8859-4.cset
│   │   ├── iso-8859-5.cmap
│   │   ├── iso-8859-5.cset
│   │   ├── iso-8859-6.cmap
│   │   ├── iso-8859-6.cset
│   │   ├── iso-8859-7.cmap
│   │   ├── iso-8859-7.cset
│   │   ├── iso-8859-8.cmap
│   │   ├── iso-8859-8.cset
│   │   ├── iso-8859-9.cmap
│   │   ├── iso-8859-9.cset
│   │   ├── ispell
│   │   ├── koi8-r.cmap
│   │   ├── koi8-r.cset
│   │   ├── koi8-u.cmap
│   │   ├── koi8-u.cset
│   │   ├── none.amf
│   │   ├── nroff-filter.info
│   │   ├── nroff-filter.so
│   │   ├── nroff.amf
│   │   ├── perl.amf
│   │   ├── sgml-filter.info
│   │   ├── sgml-filter.so
│   │   ├── sgml.amf
│   │   ├── spell
│   │   ├── split.kbd
│   │   ├── standard.kbd
│   │   ├── tex-filter.info
│   │   ├── tex-filter.so
│   │   ├── tex.amf
│   │   ├── texinfo-filter.info
│   │   ├── texinfo-filter.so
│   │   ├── texinfo.amf
│   │   └── url.amf
│   ├── libaspell.15.dylib
│   ├── libaspell.dylib -> libaspell.15.dylib
│   ├── libpspell.15.dylib
│   └── libpspell.dylib -> libpspell.15.dylib
└── share
    ├── info
    │   ├── aspell-dev.info
    │   └── aspell.info
    └── man
        └── man1
            ├── aspell-import.1
            ├── aspell.1
            ├── prezip-bin.1
            ├── pspell-config.1
            ├── run-with-aspell.1
            └── word-list-compress.1

9 directories, 183 files
```

**Comment by YorickPeterse** [comment]
Hm weird, based on that output it should be able to find `libaspell`. I'm not sure how to fix this though :disappointed:

**Comment by petems** [comment]
@YorickPeterse I think I have a solution, PR incoming :smile

**Comment by petems** [comment]
This is actually pretty similar to #23, probably will need similar logic to find the Windows path

**Comment by petems** [comment]
Taken from #31 PR comment:

Boxen is just a framework where homebrew is moved to a different directory (/opt/boxen over /usr/local, so it's the same problem for both really, just a difference in pathing)

Linking is just the symlink to the lib directory from the "Cellar" where things are actually installed:

$ brew unlink aspell && brew link aspell
Unlinking /opt/boxen/homebrew/Cellar/aspell/0.60.6.1... 24 symlinks removed
Linking /opt/boxen/homebrew/Cellar/aspell/0.60.6.1... 24 symlinks created
$ ll /opt/boxen/homebrew/lib/libaspell.dylib
lrwxr-xr-x  1 petersouter  staff  45 Mar 12 20:41 /opt/boxen/homebrew/lib/libaspell.dylib -> ../Cellar/aspell/0.60.6.1/lib/libaspell.dylib
Unfortunately changing the file name but not specifying the brew path does not fix the issue. The following all give the same error:

ffi_lib ['aspell', 'libaspell.so.15', 'libaspell']
/opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'aspell': dlopen(aspell, 5): image not found. (LoadError)
Could not open library 'libaspell.dylib': dlopen(libaspell.dylib, 5): image not found.
Could not open library 'libaspell.so.15': dlopen(libaspell.so.15, 5): image not found.
Could not open library 'libaspell.so.15.dylib': dlopen(libaspell.so.15.dylib, 5): image not found.
Could not open library 'libaspell': dlopen(libaspell, 5): image not found```
My path also has the lib directory in it:

echo $PATH | grep /opt/boxen/homebrew/lib/
/usr/local/heroku/bin:bin:/opt/boxen/packer:/opt/boxen/heroku/bin:/opt/boxen/rbenv/shims:/opt/boxen/rbenv/bin:/opt/boxen/ruby-build/bin:/opt/boxen/nodenv/bin:/opt/boxen/node-build/bin:/opt/boxen/homebrew/bin:/opt/boxen/homebrew/sbin:/opt/boxen/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/opt/puppetlabs/bin:/Users/petersouter/projects/bin:/opt/boxen/homebrew/lib/

So, as you say, this is some issue with homebrew. I've posted a thread on their forum about it to see if anyone has any ideas.

**Comment by petems** [comment]
Alright, after all that, just simlinking into `/usr/local` fixed everything...

I've added that note to the PR for the other brew command fixes: #32

**Comment by YorickPeterse** [comment]
@petems Ah, in that case do you want to add `libaspell` to the list of libraries to search for? Once that's merged in I'll push a new Gem release.

**Comment by petems** [comment]
@YorickPeterse Turns out there's no need: there seems to be some FFI magic that works out that you're on an OSX machine and changes the name automatically:

```
1] pry(FFI::Aspell)> ffi_lib ['aspell', 'libaspell.so.15']
=> [#<FFI::DynamicLibrary:0x007fc363c203c0 @name="libaspell.dylib">]
[2] pry(FFI::Aspell)>
```

**Comment by YorickPeterse** [comment]
@petems Ah, great!
