### ISSUE TITLE
Segfault when setting mode

### ISSUE THREAD

**Issue by petems** [YorickPeterse/ffi-aspell#34]
```ruby
require 'ffi/aspell'

speller = ::FFI::Aspell::Speller.new('en_US')

speller.suggestion_mode = 'normal'

#speller.set('mode', 'html')

puts speller.correct?('foo')
#=> true
```

```ruby
require 'ffi/aspell'

speller = ::FFI::Aspell::Speller.new('en_US')

speller.suggestion_mode = 'normal'

speller.set('mode', 'html')

puts speller.correct?('foo')
```

```
/opt/rubies/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb:219: [BUG] Segmentation fault at 0x0000000000001b
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0017 e:000016 CFUNC  :speller_check
c:0003 p:0080 s:0011 e:000010 METHOD /opt/rubies/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb:219
c:0002 p:0074 s:0006 E:001d28 EVAL   segfault.rb:11 [FINISH]
c:0001 p:0000 s:0002 E:000300 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
segfault.rb:11:in `<main>'
/opt/rubies/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb:219:in `correct?'
/opt/rubies/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb:219:in `speller_check'

-- Machine register context ------------------------------------------------
 rax: 0x0000000000000003 rbx: 0x00007feba3103628 rcx: 0x00007feba3103668
 rdx: 0x0000000000000003 rdi: 0x00007feba2f93530 rsi: 0x00007feba38a1138
 rbp: 0x00007fff5cdad620 rsp: 0x00007fff5cdad600  r8: 0x00007feba2cd2730
  r9: 0xffff80145d32d8f6 r10: 0x00007fff5cdad5c0 r11: 0x00000001035082d1
 r12: 0x0000000000000001 r13: 0x0000000000000003 r14: 0x00007feba2f9aa60
 r15: 0x0000000000000000 rip: 0x00000001034d3e29 rfl: 0x0000000000010216

-- C level backtrace information -------------------------------------------
0   ruby                                0x0000000102ffbd14 rb_vm_bugreport + 388
1   ruby                                0x0000000102e9752a rb_bug_context + 490
2   ruby                                0x0000000102f6c2f4 sigsegv + 68
3   libsystem_platform.dylib            0x00007fff9a58a52a _sigtramp + 26
4   libaspell.dylib                     0x00000001034d3e29 _ZN7acommon7Convert15generic_convertEPKciRNS_6StringE + 67
5   libaspell.dylib                     0x00000001035082fb aspell_speller_check + 42
6   libffi.dylib                        0x00007fff9b6c5f14 ffi_call_unix64 + 76
7   libffi.dylib                        0x00007fff9b6c679b ffi_call + 923
8   ffi_c.bundle                        0x00000001034abd55 rbffi_CallFunction + 229
9   ffi_c.bundle                        0x00000001034af889 custom_trampoline + 25
10  ruby                                0x0000000102ff1f5a vm_call_cfunc + 314
11  ruby                                0x0000000102fdc72f vm_exec_core + 10175
12  ruby                                0x0000000102fec79a vm_exec + 122
13  ruby                                0x0000000102ea0048 ruby_exec_internal + 152
14  ruby                                0x0000000102e9ff56 ruby_run_node + 54
15  ruby                                0x0000000102e5255f main + 79

-- Other runtime information -----------------------------------------------

* Loaded script: segfault.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/x86_64-darwin15/enc/encdb.bundle
    5 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/x86_64-darwin15/enc/trans/transdb.bundle
    6 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/unicode_normalize.rb
    7 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/x86_64-darwin15/rbconfig.rb
    8 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/compatibility.rb
    9 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/defaults.rb
   10 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/deprecate.rb
   11 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/errors.rb
   12 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/version.rb
   13 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/requirement.rb
   14 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/platform.rb
   15 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/basic_specification.rb
   16 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/stub_specification.rb
   17 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/util/list.rb
   18 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/x86_64-darwin15/stringio.bundle
   19 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb
   20 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/exceptions.rb
   21 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/dependency.rb
   22 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb
   23 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb
   24 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb
   25 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems.rb
   26 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/path_support.rb
   27 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/version.rb
   28 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb
   29 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/levenshtein.rb
   30 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/jaro_winkler.rb
   31 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkable.rb
   32 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/2.3.0/delegate.rb
   33 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   34 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   35 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   36 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   37 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/null_checker.rb
   38 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/formatter.rb
   39 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean.rb
   40 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi_c.bundle
   41 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/platform.rb
   42 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/types.rb
   43 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/library.rb
   44 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/errno.rb
   45 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/pointer.rb
   46 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/memorypointer.rb
   47 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/struct_layout_builder.rb
   48 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/struct.rb
   49 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/union.rb
   50 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/managedstruct.rb
   51 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/callback.rb
   52 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/io.rb
   53 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/autopointer.rb
   54 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/variadic.rb
   55 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/enum.rb
   56 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/ffi.rb
   57 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi.rb
   58 /opt/rubies/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/aspell.rb
   59 /opt/rubies/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/error.rb
   60 /opt/rubies/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb
   61 /opt/rubies/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/version.rb
   62 /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6
```

**Comment by petems** [comment]
The following spec can trigger the segfault:

```
it 'sets the mode of the speller' do
      @speller.set('mode', 'html')

      expect(@speller.get('mode')).to eq('html')

      expect(@speller.correct?('hello')).to eq(true)
    end
```

**Comment by petems** [comment]
HTML mode appears avaliable:

```
$ aspell dump modes
ccpp           mode for checking C++ comments and string literals
comment        mode to check any lines starting with a #
email          mode for skipping quoted text in email messages
html           mode for checking HTML documents
none           mode to disable all filters
nroff          mode for checking Nroff documents
perl           mode for checking Perl comments and string literals
sgml           mode for checking generic SGML/XML documents
tex            mode for checking TeX/LaTeX documents
texinfo        mode for checking Texinfo documents
url            mode to skip URL like constructs (default mode)
```

**Comment by petems** [comment]
```
$ uname -a 
Linux ubuntu-test 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ ruby -e "require 'ffi/aspell';speller = ::FFI::Aspell::Speller.new('en_US');speller.set('mode', 'html');puts speller.correct?('foo');"
true
```

```
$ Darwin Peters-MacBook-Pro-4.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64
$ /opt/rubies/2.3.3/lib/ruby/gems/2.3.0/gems/ffi-aspell-1.1.0/lib/ffi/aspell/speller.rb:219: [BUG] Segmentation fault at 0x00000000000000
```

**Comment by petems** [comment]
Raised a Ruby bug: https://bugs.ruby-lang.org/issues/13327

**Comment by YorickPeterse** [comment]
@petems I don't think that's a bug with Ruby itself, I think it's more likely something is wrong with Aspell on OS X.

**Comment by petems** [comment]
@YorickPeterse It's likely, but I checked with some Ruby folk, and they said segfaults are worth logging tickets over, regardless of the libraries. 

Many upstream Ruby bugs on OSX have been fixed from issues discovered in libraries: https://bugs.ruby-lang.org/search?page=2&q=Crash+Report+log+information&utf8=%E2%9C%93

**Comment by petems** [comment]
Looks like this has been around for a while: http://stackoverflow.com/questions/11356249/simple-spell-check-method-gem-in-ruby/11379089#11379089
